{{- if .Values.etcd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-defense.fullname" . }}-etcd-headless
  labels:
    {{- include "aether-defense.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
spec:
  type: {{ .Values.etcd.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.etcd.service.clientPort }}
    targetPort: client
    protocol: TCP
    name: client
  - port: {{ .Values.etcd.service.peerPort }}
    targetPort: peer
    protocol: TCP
    name: peer
  selector:
    {{- include "aether-defense.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-defense.fullname" . }}-etcd
  labels:
    {{- include "aether-defense.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.etcd.service.port }}
    targetPort: client
    protocol: TCP
    name: client
  selector:
    {{- include "aether-defense.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
{{- end }}
